### PR TITLE
Fix ElementPart when IE reorders attrs. Fixes #1537

### LINKED ISSUE #1537: [lit-next] Element bindings can fail on IE11
This construction fails:

```
html`<div slot=${slot} ${ref(myRef)}></div>`
```

but this is ok:

```
html`<div ${ref(myRef)} slot=${slot}></div>`
```

### PR DESCRIPTION
**Pull request by kevinpschaaf**
Fix `ElementPart` when IE reorders attributes. The `attrNames` array now holds `undefined` for `ElementPart`s, and uses the same logic as `AttributePart` to ensure parts are created in the original order, despite bound attributes possibly being re-ordered.

Also adds SSR support for `ElementPart`, and adds belated SSR adds tests for `ElementPart`, `DisconnectableDirective`, and nested directives also.

Uncompressed code size when up a tad but gzip/brotli went down:

```
Name                            Size       Minified   Gzipped    Brotli    
---------------------------------------------------------------------------
lit-html.js                     6.086 KB   6.078 KB   2.759 KB   2.501 KB
lit-html.js                     6.101 KB   6.093 KB   2.758 KB   2.488 KB  
```

Fixes #1537

### CODE REVIEW

File: packages/lit-html/src/lit-html.ts [hunk 1]
```diff
@@ -491,7 +494,7 @@ const getTemplateHtml = (
           s.slice(0, attrNameEndIndex) +
             boundAttributeSuffix +
             s.slice(attrNameEndIndex)) + marker
-        : s + marker + (attrNameEndIndex === -2 ? `:${i}` : '');
```
Comment (kevinpschaaf) [inline packages/lit-html/src/lit-html.ts:494]: I removed the `:` here to economize on a couple bytes since I knew I was adding a bit... Don't think it's required.

**Review by justinfagnani — APPROVED** [review]
