### PR TITLE
fix(lit-html): handle `undefined` arg on disconnect for ref directive 

### LINKED ISSUE #5217: Ref directive does not san-check its stored arg on disconnected/reconnected lifecycle
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

❓ is the ref directive supposed to accept an undefined for argument?
Looks like that yes based on the exported types (that are derived from [here](https://github.com/lit/lit/blob/f243134b226735320b61466cebdaf0c1e574bfa7/packages/lit-html/src/directives/ref.ts#L48)
However, both the disconnected & reconnected lifecyles are doing unsafe usage of the ref.

I'll be glad to bring a fix upstream for that 🙂
However, I see two possible fixes, and I'd like to see which one we want to go with:
Either we consider the issue to be the looseness of the argument, and restrict it from RefCallback|undefined to RefCallback
Or, we go the opposite way and we ensure the internal _ref property is used safely.****

### Reproduction

https://lit.dev/playground/#sample=examples%2Fhello-world&gist=0b002ac6df87f09ff2344481e719cce4
1. Open DevTools
2. Check the console
3. It throw a runtime error

### Workaround

Marshall value prior to using the directive, `<div ${arg ? ref(arg) : nothing}></div>`  

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

3.3.1

### Browser/OS/Node environment

Browser: Chrome 144.0.7559.97
OS: macOS 26.2 (25C56)

### PR DESCRIPTION
**Pull request by louis-bompart**
When `ref` is called with `undefined` for arg and the element where the ref has been render in disconnect, the disconnect method tried to call `this._ref.value`, where `this._ref` being undefined, causing an error.

The `_updateRefValue` method in essence currently already sieve thru the various type of the `_ref` member. This PR handles the `undefined` case by returning early. 

Fixes #5217

### CODE REVIEW

File: packages/lit-html/src/directives/ref.ts [hunk 1]
```diff
@@ -51,7 +51,7 @@ class RefDirective extends AsyncDirective {
 
   override update(part: ElementPart, [ref]: Parameters<this['render']>) {
     const refChanged = ref !== this._ref;
-    if (refChanged && this._ref !== undefined) {
+    if (refChanged) {
```
Comment (louis-bompart) [inline packages/lit-html/src/directives/ref.ts:54]: Maybe an over-optimization, but we would have been checking twice whether `this._ref` is undefined in this code path.
Given that `_updateRefValue` handles it after my change, I removed this part of the condition.

File: .changeset/sweet-garlics-behave.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'lit-html': patch
+---
```
Comment (augustjk) [inline .changeset/sweet-garlics-behave.md:4]: to make sure the main lit package also gets a bump
```suggestion
---
'lit': patch
'lit-html': patch
---
```

Comment (louis-bompart) [reply .changeset/sweet-garlics-behave.md:4]: I did consider, but the changeset CLI does mention that the patch would've been propagated to the consumer of lit-html, such as lit.
But it ain't an issue either so 👍
