### PR TITLE
Fix for bindings before end of self-closing tags

### LINKED ISSUE #1594: [lit-html] Regression: event bindings right before self-closing tag ends are broken
Example

```ts
html`<input @click=${listener}/>`
```

We don't support this well for attribute/property bindings - they will include the `"/"` in the value - but this does work for events in 1.x. If we fix this binding position in general it would be a nice improvement.

### PR DESCRIPTION
**Pull request by justinfagnani**
Fixes #1594 and adds support for bindings like:

```ts
html`<input .value=${v}/>`
```

### CODE REVIEW

File: packages/lit-html/src/lit-html.ts [hunk 1]
```diff
@@ -494,17 +494,24 @@ const getTemplateHtml = (
     //  4. We're somewhere else inside the tag. If we're in attribute name
     //     position (attrNameEndIndex === -2), add a sequential suffix to
     //     generate a unique attribute name.
+
+    // Detect a binding next to self-closing tag end and insert a space to
+    // separate the marker from the tag end:
+    const end =
+      regex === tagEndRegex && strings[i + 1].startsWith('/>') ? ' ' : '';
```
Comment (jridgewell) [inline packages/lit-html/src/lit-html.ts:501]: Nit: ? Could we simplify this and just always insert a space?

**Review by jridgewell — APPROVED** [review]

File: packages/lit-html/src/lit-html.ts (hunk 1 above)
Comment (justinfagnani) [reply packages/lit-html/src/lit-html.ts:501]: We can't because the current regex is `tagEndRegex` for unquoted attributes, _and_ we also support multiple bindings in an unquoted attribute now, like `<div foo=${a}${b}></div>`. We can't insert a space after the first binding as that'll close the attribute early.

**Review by kevinpschaaf — APPROVED** [review]
