### PR TITLE
Handle CSS variables in styleMap

### LINKED ISSUE #632: Can't set CSS variables with styleMap directive
The styleMap directive does not work with custom CSS properties. Box 2 should be the same size as Box 1 when you click update.

https://codepen.io/osublake/pen/jQwVyQ

### PR DESCRIPTION
**Pull request by justinfagnani**
Fixes #632

### CODE REVIEW

File: src/directives/styleMap.ts [hunk 1]
```diff
@@ -60,6 +60,13 @@ export const styleMap = directive((styleInfo: StyleInfo) => (part: Part) => {
       ((part.committer.element as HTMLElement).style as any)[name] = null;
```
Comment (kevinpschaaf) [inline src/directives/styleMap.ts]: I think you need the same `--` check here for removal as well.

While you're at it, seems like the `part.committer.element as HTMLElement).style` expression can be pulled out earlier and used for both places.

**Comment by justinfagnani** [comment]
@kevinpschaaf PTAL
