### PR TITLE
Don't disturb imperatively added classes in classMap

### LINKED ISSUE #1111: classMap doesn't preserve imperatively added classes
# Description

While imperatively changing classes that are managed by classMap _shouldn't_ be a supported feature, the previous version of classMap supported it to an extent, and the new version removes imperatively added classes in more situations. This has caused internal test failures at Google.

# Steps to Reproduce

1. Write this code

```ts
const go = (classes) => render(html`<div id="a" class=${classMap(classes)}></div>`, document.body);
go({foo: true});
const el = document.querySelector('#a');
el.classList.add('bar');

go({foo: false});
el.classList.contains('bar'); // false 😢
```

## Browsers Affected
All

### PR DESCRIPTION
**Pull request by justinfagnani**
Fixes #1111

Revert classMap to previous implementation, but don't use classList or className.

### CODE REVIEW

File: src/test/directives/class-map_test.ts [hunk 1]
```diff
@@ -81,14 +81,24 @@ suite('classMap', () => {
     assert.isFalse(el.classList.contains('foo'));
   });
 
-  test('can override static classes', () => {
```
Comment (justinfagnani) [inline src/test/directives/class-map_test.ts]: This behavior was never released so it's safe to change. With the implementation in this PR, static classes are always present, even if they're apparently overridden in the classMap. I think this behavior is fine - it should be very rare that a class is in both static and dynamic sets, but if someone was doing this then changing it would have been a breaking change.

File: src/directives/class-map.ts [hunk 2]
```diff
@@ -66,55 +48,44 @@ export const classMap = directive((classInfo: ClassInfo) => (part: Part) => {
...
-    }
-    changed = true;
+    // Write static classes once
+    // Use setAttribute() because className isn't a string on SVG elements
+    element.setAttribute('class', committer.strings.join(' '));
+    previousClassesCache.set(part, previousClasses = new Set());
   }
 
+  // IE11 doesn't support classList on SVG elements, so we emulate it with a Set
+  const classes = new Set((element.getAttribute('class') || '').split(/\s+/));
```
Comment (jridgewell) [inline src/directives/class-map.ts]: We had a bug before about `Set` not supporting iterable in the constructor.

File: src/directives/class-map.ts [hunk 3]
```diff
@@ -66,55 +48,44 @@ export const classMap = directive((classInfo: ClassInfo) => (part: Part) => {
...
+      changed = true;
     }
   });
 
-  // Add or remove classes based on their ClassInfo value
+  // Add or remove classes based on their classMap value
   for (const name in classInfo) {
     const value = classInfo[name];
-    const cached = previousClasses.get(name);
     // We explicitly want a loose truthy check of `value` because it seems more
```
Comment (jridgewell) [inline src/directives/class-map.ts]: This comment now applies to the `if (value)` statement inside this if statement.

File: src/test/directives/class-map_test.ts [hunk 4]
```diff
@@ -81,14 +81,24 @@ suite('classMap', () => {
...
+    renderClassMap({foo: true});
+    const el = container.firstElementChild!;
+    assert.isTrue(el.classList.contains('foo'));
+
+    el.classList.add('bar');
+    assert.isTrue(el.classList.contains('bar'));
+
+    renderClassMap({foo: false});
+    assert.isFalse(el.classList.contains('foo'));
+    assert.isTrue(el.classList.contains('bar'));
```
Comment (jridgewell) [inline src/test/directives/class-map_test.ts]: Is this a behavior we actually want to support? I think lit takes complete ownership of every other attribute.

File: src/directives/class-map.ts (hunk 2 above)
Comment (justinfagnani) [reply src/directives/class-map.ts]: I remember that too, but checked MDN and tried it... maybe that's the Chrome 41 error too.

File: src/test/directives/class-map_test.ts (hunk 4 above)
Comment (justinfagnani) [reply src/test/directives/class-map_test.ts]: I know, but this change caused several failures in Google tests. Fixing them requires architectural change that I can't do right now.

**Comment by justinfagnani** [comment]
I added the ponyfill. Running through tests now
