### PR TITLE
Fix style attribute bindings in IE

### LINKED ISSUE #450: Bindings in style attribute broken in IE
Because IE rewrites the style attribute.

### PR DESCRIPTION
**Pull request by justinfagnani**
Fixes #450

### CODE REVIEW

**Comment by ruphin** [comment]
Creative solution to the IE11 style problem. I like it :)

**Comment by justinfagnani** [comment]
@sorvell tests passing now, PTAL

File: src/lib/template-result.ts [hunk 1]
```diff
@@ -55,6 +55,13 @@ export class TemplateResult {
       // "...": no change. open === -1, close === -1
       isTextBinding =
           (close > -1 || isTextBinding) && s.indexOf('<', close + 1) === -1;
+
+      // IE does a bad. Work around it.
```
Comment (sorvell) [inline src/lib/template-result.ts]: A better explanation would help =)
