### PR TITLE
[lit-next] Upgrade to TypeScript 4.1.3

### LINKED ISSUE #1491: [lit-next] Builds fail when upgrading to latest TypeScript
After removing the package-lock and installing, builds fail for at least for ReactiveElement and LitElement. It looks like this might be TypeScript version related.

The code should work with the latest TypeScript.

### PR DESCRIPTION
**Pull request by sorvell**
Fixes #1491. The latest version of TypeScript is a little more strict around `unknown` types which required some minor tweaks.

### CODE REVIEW

File: packages/lit-html/src/lit-html.ts [hunk 1]
```diff
@@ -124,7 +124,7 @@ const isArray = Array.isArray;
 const isIterable = (value: unknown): value is Iterable<unknown> =>
   isArray(value) ||
   // eslint-disable-next-line @typescript-eslint/no-explicit-any
-  (value && typeof (value as any)[Symbol.iterator] === 'function');
+  ((value && typeof (value as any)[Symbol.iterator] === 'function') as boolean);
```
Comment (justinfagnani) [inline packages/lit-html/src/lit-html.ts:127]: I wonder if we should write this as `typeof (value as any)?.[Symbol.iterator] === 'function'`

File: packages/reactive-element/src/reactive-element.ts [hunk 2]
```diff
@@ -737,7 +737,7 @@ export abstract class ReactiveElement extends HTMLElement {
    * overridden on the element instance with a function that triggers the first
    * update.
    */
-  protected enableUpdating() {}
+  protected enableUpdating(_value: boolean) {}
```
Comment (justinfagnani) [inline packages/reactive-element/src/reactive-element.ts:740]: why was this needed? Can you make it optional to leave out the `true` constant above?

**Review by justinfagnani — APPROVED** [review]

File: packages/lit-html/src/lit-html.ts (hunk 1 above)
Comment (sorvell) [reply packages/lit-html/src/lit-html.ts]: Done and this removed the need for the cast.

File: packages/reactive-element/src/reactive-element.ts (hunk 2 above)
Comment (sorvell) [reply packages/reactive-element/src/reactive-element.ts]: Done.

File: packages/reactive-element/src/test/reactive-element_test.ts [hunk 3]
```diff
@@ -2197,13 +2197,13 @@ suite('ReactiveElement', () => {
       promiseFulfilled = false;
 
       get updateComplete() {
-        return (async () => {
+        return (async (): Promise<boolean | void> => {
```
Comment (kevinpschaaf) [inline packages/reactive-element/src/test/reactive-element_test.ts:2200]: Seems like you changed this to not resolve to `boolean`?

File: packages/reactive-element/src/test/reactive-element_test.ts [hunk 4]
```diff
@@ -2294,7 +2294,7 @@ suite('ReactiveElement', () => {
   });
 
   test('can override performUpdate()', async () => {
-    let resolve: (() => void) | undefined;
+    let resolve: ((value?: boolean) => void) | undefined;
```
Comment (kevinpschaaf) [inline packages/reactive-element/src/test/reactive-element_test.ts:2297]: Also never resolved to a `boolean`?

**Review by kevinpschaaf — COMMENTED** [review]
Some minor nits; it's possible I'm just misunderstanding.

**Review by abdonrd — COMMENTED** [review]
As you are in a mono-repo, why not remove the `typescript` dependency from the packages? With the root `package.json` should be enough and more easy to mantain.

File: packages/reactive-element/src/test/reactive-element_test.ts (hunk 4 above)
Comment (sorvell) [reply packages/reactive-element/src/test/reactive-element_test.ts:2297]: Changed to `unknown`. It appears the promise resolver argument is now required.

File: packages/reactive-element/src/test/reactive-element_test.ts (hunk 3 above)
Comment (sorvell) [reply packages/reactive-element/src/test/reactive-element_test.ts:2200]: Removed. The `updateComplete` promise previously resolved to `unknown`. This was changed and now reverted back.

It normally resolves to a boolean but the first one resolves to `undefined` and it it's maybe not worth changing that?

Comment (kevinpschaaf) [reply packages/reactive-element/src/test/reactive-element_test.ts]: Hmm, if we're going to resolve to a boolean, shouldn't the initial `updateComplete` correctly reflect the `isUpdatePending` state? If that's intended to be a useful thing, seems bad if you can't rely on that to know if a further update was enqueued on the first render, only on subsequent ones.

It sort of points out that the gambit of just making `enableProperties` be the initial `__updatePromise` resolver is maybe too simplistic, since we're not actually resolving after `performUpdate()` is done; it just sort of works because a user's `await el.updateComplete` will be the second thing queued behind the `await this.__updatePromise` in `__enqueueUpdate()`. We should really be waiting to resolve the `__updatePromise` after `performUpdate` when we know the `isUpdatePending` state.

It feels like we should be able to refactor a little to use the new `__pendingConnectionPromise` now to do the initial connection holdoff as well, maybe?

Let's make an issue and not block, but seems like we should fix that or remove the boolean, one or the other.

**Comment by kevinpschaaf** [comment]
@abdonrd Since we run the build scripts per-package (and I think we want to keep that way, at least for now), it'd take a little more work to run tsc, rollup, etc. from the top level. We may consider that in a subsequent PR.

**Comment by abdonrd** [comment]
@kevinpschaaf got it, thanks Kevin! New PR: https://github.com/Polymer/lit-html/pull/1498
