### PR TITLE
Shady render fix

### LINKED ISSUE #326: shady-render does not work with ApplyShim or the CSS Custom Property shim (IE11)
There are 2 related issues here:
1. `styleElement` is currently never called and is required for the ApplyShim or Custom Property shim (IE11) to work correctly
1. Calling `prepareTemplate` multiple times as `shady-render` does is incompatible with `styleElement`

So, to address this, we'll need to call `prepareTemplate` only once per element type and figure out when/how to call `styleElement` within rendering.

### PR DESCRIPTION
**Pull request by sorvell**
Fixes #326 by imposing a limitation that styles for a scope name can only be supplied in the initial render of that shadowRoot. This is required because `ShadyCSS` can only prepare styles for a scope once to properly track styles in that scope and process custom properties when polyfilled and @apply.

Styles are processed based on initial scope rendering, but templated DOM within a scope will always be correctly given a scoping class. 

Note that styles in the first render of a scope can contain lit parts. This is useful for one-time bindings.

**Warning:** merge only after [this ShadyCSS PR](https://github.com/webcomponents/shadycss/pull/183) is merged and released.

### CODE REVIEW

File: src/lib/shady-render.ts [hunk 1]
```diff
@@ -22,31 +23,83 @@ declare global {
...
+            // insert style into rendered fragment
+            fragment.insertBefore(style, fragment.firstChild);
+            // insert into lit-template (for subsequent renders)
+            const template = templateFactory(result);
+            insertNodeIntoTemplate(template, style.cloneNode(true),
+                template.element.content.firstChild);
+          }
+        }
+      }
+      window.ShadyCSS.styleElement(host);
```
Comment (smalluban) [inline src/lib/shady-render.ts]: For the first time calling `ShadyCSS.styleElement()` is ok, but if a change is made to the template and value of CSS custom property is changed, `ShadyCSS.styleSubtree()` has to be called to update nested elements using those CSS custom properties.

For example: 
```javascript
template = (active) => html`
  <style>
     my-button {
       --custom-color: red;
     }
     my-button.active {
       --custom-color: blue;
     }
  </style>
  <my-button class="${active ? 'active' : ''}"></my-button>
`;
```
Without calling `styleSubtree`, after change `active` to `true` in IE11 `<my-button>` will be still red.

**Comment by abdonrd** [comment]
Any plan to replace the `@apply` with some `::part` and `::theme` polyfill?
I think new elements with LitElement should avoid deprecated things like `@apply`.

File: src/lib/shady-render.ts (hunk 1 above)
Comment (sorvell) [reply src/lib/shady-render.ts]: There's not a spot to do this in lit-html, but it does deserve documentation since it is necessary. It will be handled separately in LitElement.

Comment (smalluban) [reply src/lib/shady-render.ts]: But there is a spot... You actually put `window.ShadyCSS.styleElement(host)` here. It has to be simply changed to `styleSubtree` to update all nested elements as well. I think it is very low-level API and LitElement using lit-html won't be able to do anything with that.

Comment (sorvell) [reply src/lib/shady-render.ts]: The call to `styleElement` is only made when a lit `TemplateInstance` is created, not updated. Typically this is first render only, and this is done for efficiency. Therefore, changing this to `styleSubtree` wouldn't help with the case outlined here.

In general, ShadyCSS [requires](https://github.com/webcomponents/shadycss#usage) calling `ShadyCSS.styleSubtree` when dynamic updates that affect custom properties are made. This is specifically for the custom property shim which is only needed on IE11.

Calling `ShadyCSS.styleSubtree` is not cheap and doing so on every call to `shady-render` would have a pretty negative performance impact. For this reason, it seems better **not** to handle this case generally in `shady-render` and instead require users to call `ShadyCSS.styleSubtree` when needed. This is not ideal but seems like the best tradeoff.

File: src/lib/shady-render.ts [hunk 2]
```diff
@@ -22,31 +23,83 @@ declare global {
...
 
 export function render(
     result: TemplateResult,
     container: Element|DocumentFragment,
     scopeName: string) {
-  return baseRender(result, container, shadyTemplateFactory(scopeName));
+  const host = hostForNode(container);
+  if (host && typeof window.ShadyCSS === 'object') {
+    const templateFactory = shadyTemplateFactory(scopeName);
+    const renderer = (container: Element|DocumentFragment, fragment: DocumentFragment) => {
```
[the remark this answers is not in the document]
Comment (justinfagnani) [reply src/lib/shady-render.ts]: Talked offline, and it seems better to copy & paste the contents of render() for now, rather than expose an unstable API in the form of the renderDOM callback

File: src/lib/modify-template.ts [hunk 3]
```diff
@@ -0,0 +1,82 @@
...
+ * The complete set of contributors may be found at
+ * http://polymer.github.io/CONTRIBUTORS.txt
+ * Code distributed by Google as part of the polymer project is also
+ * subject to an additional IP rights grant found at
+ * http://polymer.github.io/PATENTS.txt
+ */
+
+import {Template} from '../lit-html.js';
+
+export function removeNodesFromTemplate(template: Template, nodes: Node[]) {
```
[the remark this answers is not in the document]
Comment (sorvell) [reply src/lib/modify-template.ts]: done

File: src/lib/modify-template.ts [hunk 4]
```diff
@@ -0,0 +1,82 @@
...
+  const {element: {content}, parts} = template;
+  const walker = document.createTreeWalker(
+    content,
+    NodeFilter.SHOW_ELEMENT | NodeFilter.SHOW_COMMENT |
+        NodeFilter.SHOW_TEXT,
+    null as any,
+    false);
+  let nodesIndex = 0;
```
[the remark this answers is not in the document]
Comment (sorvell) [reply src/lib/modify-template.ts]: refactored

File: src/lib/modify-template.ts [hunk 5]
```diff
@@ -0,0 +1,82 @@
...
+  let nodeToFind = nodes[nodesIndex];
```
[the remark this answers is not in the document]
Comment (sorvell) [reply src/lib/modify-template.ts]: refactored

File: src/lib/modify-template.ts [hunk 6]
```diff
@@ -0,0 +1,82 @@
...
+  let partIndex = 0;
+  let part = parts[partIndex];
+  let partDelta = 0;
+  let disableUntil = 0;
```
[the remark this answers is not in the document]
Comment (sorvell) [reply src/lib/modify-template.ts]: refactored

File: src/lib/modify-template.ts [hunk 7]
```diff
@@ -0,0 +1,82 @@
...
+  const walker = document.createTreeWalker(
+    content,
+    NodeFilter.SHOW_ELEMENT | NodeFilter.SHOW_COMMENT |
+        NodeFilter.SHOW_TEXT,
+    null as any,
+    false);
+  let nodesIndex = 0;
+  let nodeToFind = nodes[nodesIndex];
+  let partIndex = 0;
+  let part = parts[partIndex];
```
[the remark this answers is not in the document]
Comment (sorvell) [reply src/lib/modify-template.ts]: refactored

File: src/lib/modify-template.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (sorvell) [reply src/lib/modify-template.ts]: refactored

File: src/lib/modify-template.ts [hunk 8]
```diff
@@ -0,0 +1,82 @@
...
+  let partDelta = 0;
+  let disableUntil = 0;
+  const nodesToRemove: Node[] = [];
+  let index = -1;
+  while (walker.nextNode()) {
+    index++;
+    const node = walker.currentNode as Element;
+    if (node === nodeToFind) {
+      nodeToFind = nodes[++nodesIndex];
+      const removeCount = node.childNodes.length + 1;
```
[the remark this answers is not in the document]
Comment (sorvell) [reply src/lib/modify-template.ts]: refactored to fix but needs tests.

File: src/lib/modify-template.ts [hunk 9]
```diff
@@ -0,0 +1,82 @@
...
+      disableUntil = index + removeCount;
+      partDelta -= removeCount;
+      nodesToRemove.push(node);
+    }
+    // adjust part indices or disable parts.
+    while (part && part.index === index) {
+      if (index < disableUntil) {
+        part.index = -1;
```
[the remark this answers is not in the document]
Comment (sorvell) [reply src/lib/modify-template.ts]: Added a specific method and comment.

File: src/lib/modify-template.ts [hunk 10]
```diff
@@ -0,0 +1,82 @@
...
+    null as any,
+    false);
+  let nodesIndex = 0;
+  let nodeToFind = nodes[nodesIndex];
+  let partIndex = 0;
+  let part = parts[partIndex];
+  let partDelta = 0;
+  let disableUntil = 0;
+  const nodesToRemove: Node[] = [];
+  let index = -1;
```
[the remark this answers is not in the document]
Comment (sorvell) [reply src/lib/modify-template.ts]: renamed

File: src/lib/shady-render.ts [hunk 11]
```diff
@@ -22,31 +23,83 @@ declare global {
...
+}
 
-        template = new Template(result, element);
-        templateCache.set(result.strings, template);
-      }
-      return template;
-    };
+const shadyRenderSet = new Set<string>();
+
+function hostForNode(node: Node) {
```
[the remark this answers is not in the document]
Comment (sorvell) [reply src/lib/shady-render.ts]: refactored

File: src/lib/shady-render.ts [hunk 12]
```diff
@@ -22,31 +23,83 @@ declare global {
...
+  return node.nodeType === Node.DOCUMENT_FRAGMENT_NODE && (node as ShadowRoot).host
```
[the remark this answers is not in the document]
Comment (sorvell) [reply src/lib/shady-render.ts]: done

File: src/lib/shady-render.ts [hunk 13]
```diff
@@ -22,31 +23,83 @@ declare global {
...
+}
 
 export function render(
     result: TemplateResult,
     container: Element|DocumentFragment,
     scopeName: string) {
-  return baseRender(result, container, shadyTemplateFactory(scopeName));
+  const host = hostForNode(container);
+  if (host && typeof window.ShadyCSS === 'object') {
```
[the remark this answers is not in the document]
Comment (sorvell) [reply src/lib/shady-render.ts]: done

File: src/lib/shady-render.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (sorvell) [reply src/lib/shady-render.ts]: done

File: src/lib/modify-template.ts [hunk 14]
```diff
@@ -23,40 +26,57 @@ export function removeNodesFromTemplate(template: Template, nodesToRemove: Set<N
...
+  let currentRemovingNode: Node|null = null;
   while (walker.nextNode()) {
     nodeIndex++;
     const node = walker.currentNode as Element;
-    // maybe pop the stack
-    if (walker.previousSibling === removalStack[removalStack.length - 1]) {
-      removalStack.pop();
+    // end removal if stepped past the removing node
+    if (node.previousSibling === currentRemovingNode) {
+      currentRemovingNode = null;
```
Comment (justinfagnani) [inline src/lib/modify-template.ts]: I think this needs to be the next node in the stack, in the case of nested removal.

Comment (sorvell) [reply src/lib/modify-template.ts]: Added a little comment description at the top of that function. Don't think we care if it's nested since we only need to know when we're ending the removal state of a non-nested node:
* any part inside the removing node gets deactivated
* any part outside a non-nested removing node has its index adjusted

Comment (justinfagnani) [reply src/lib/modify-template.ts]: Ah, that's right.

File: src/lib/modify-template.ts [hunk 15]
```diff
@@ -0,0 +1,129 @@
...
+  let activeParts = parts.filter((part) => isTemplatePartActive(part));
+  let part = activeParts[partIndex];
+  let insertCount = 0;
+  let walkerIndex = -1;
+  while (walker.nextNode()) {
+    walkerIndex++;
+    const walkerNode = walker.currentNode as Element;
+    if (walkerNode === refNode) {
+      refNode.parentNode!.insertBefore(node, refNode);
+      insertCount = countNodes(node);
```
Comment (justinfagnani) [inline src/lib/modify-template.ts]: I think you can reuse the same walker. Not sure if that'd be faster, but it might be a bit smaller:

```ts
walker.previousSibling();
while (walker.nextNode() !== refNode) {
  insertCount++;
}
```

File: src/lib/modify-template.ts [hunk 16]
```diff
@@ -0,0 +1,129 @@
...
+    }
+    while (part !== undefined && part.index === walkerIndex) {
```
Comment (justinfagnani) [inline src/lib/modify-template.ts]: Once the node is inserted we don't have to walk the tree anymore, but can just modify the remaining part indices.

File: src/lib/modify-template.ts [hunk 17]
```diff
@@ -0,0 +1,129 @@
...
+    throw 'Reference node must be inside template.';
+  }
+  const walker = document.createTreeWalker(
+      content,
+      walkerNodeFilter,
+      null as any,
+      false);
+  let partIndex = 0;
+  // only need to modify active parts.
+  let activeParts = parts.filter((part) => isTemplatePartActive(part));
```
Comment (justinfagnani) [inline src/lib/modify-template.ts]: This check could be done in the while loop at line 124 and avoid creating another array.

File: src/lib/shady-render.ts [hunk 18]
```diff
@@ -12,19 +12,29 @@
...
 export {html, svg, TemplateResult} from '../lit-html.js';
 
 declare global {
   interface Window {
     ShadyCSS: any;
   }
+  class ShadowRoot {}
 }
 
+const getTemplateKey = (type: string, scopeName: string) =>
```
Comment (justinfagnani) [inline src/lib/shady-render.ts]: Consider a different name: `templateKey` sounds like it'd be based on the template contents... this is a key used to look up a cache.

File: src/lib/shady-render.ts [hunk 19]
```diff
@@ -33,20 +43,106 @@ const shadyTemplateFactory = (scopeName: string) =>
...
         templateCache.set(result.strings, template);
       }
       return template;
     };
 
+
+const TEMPLATE_TYPES = ['html', 'svg'];
+
+/**
+ * Removes all style elements from Templates for hte given scopeName
```
Comment (justinfagnani) [inline src/lib/shady-render.ts]: hte -> the

File: src/lib/shady-render.ts [hunk 20]
```diff
@@ -33,20 +43,106 @@ const shadyTemplateFactory = (scopeName: string) =>
...
+      // only scope element template once per scope name
+      if (!shadyRenderSet.has(scopeName)) {
+        shadyRenderSet.add(scopeName);
+        const styleTemplate = document.createElement('template');
+        Array.from(fragment.querySelectorAll('style')).forEach((s: Element) => {
+          styleTemplate.content.appendChild(s);
+        });
+        window.ShadyCSS.prepareTemplateStyles(styleTemplate, scopeName);
+        // fix templates.
+        removeStylesFromLitTemplates(scopeName);
```
Comment (justinfagnani) [inline src/lib/shady-render.ts]: Can you expand the comment to describes why the template cache contains all the templates we need to modify by this point?

File: src/lib/shady-render.ts [hunk 21]
```diff
@@ -33,20 +43,106 @@ const shadyTemplateFactory = (scopeName: string) =>
...
+ * For the given scope name, ensures that ShadyCSS style scoping is performed.
+ * This is done just once per scope name so the fragment and template cannot
+ * be modified.
+ * (1) extracts styles from the rendered fragment and hands them to ShadyCSS
+ * to be scoped and appended to the document
+ * (2) removes style elements from all lit-html Templates for this scope name.
+ */
+const ensureStylesScoped =
+    (fragment: DocumentFragment, template: Template, scopeName: string) => {
+      // only scope element template once per scope name
```
Comment (justinfagnani) [inline src/lib/shady-render.ts]: style super-nit: Let's standardize on capitalizing the comments

File: src/lib/shady-render.ts [hunk 22]
```diff
@@ -33,20 +43,106 @@ const shadyTemplateFactory = (scopeName: string) =>
...
+      if (!shadyRenderSet.has(scopeName)) {
+        shadyRenderSet.add(scopeName);
+        const styleTemplate = document.createElement('template');
+        Array.from(fragment.querySelectorAll('style')).forEach((s: Element) => {
+          styleTemplate.content.appendChild(s);
+        });
+        window.ShadyCSS.prepareTemplateStyles(styleTemplate, scopeName);
+        // fix templates.
```
Comment (justinfagnani) [inline src/lib/shady-render.ts]: nit: no period needed for non sentence

File: src/lib/shady-render.ts [hunk 23]
```diff
@@ -33,20 +43,106 @@ const shadyTemplateFactory = (scopeName: string) =>
...
+        removeStylesFromLitTemplates(scopeName);
+        // ApplyShim case.
+        if (window.ShadyCSS.nativeShadow) {
+          const style = styleTemplate.content.querySelector('style');
+          if (style) {
```
Comment (justinfagnani) [inline src/lib/shady-render.ts]: here and a couple of other places: I prefer explicit checks, like `style !== null`

File: src/test/lib/shady-render_test.ts [hunk 24]
```diff
@@ -22,50 +22,144 @@ const assert = chai.assert;
...
           span {
-            color: blue;
+            border: 5px solid tomato;
           }
         </style>
         <span>Testing...</span>
       `}
-    `, container, 'scope-2');
+    `, container.shadowRoot as DocumentFragment, 'scope-2');
+    const div = (container.shadowRoot  as DocumentFragment).querySelector('div');
```
Comment (justinfagnani) [inline src/test/lib/shady-render_test.ts]: the cast to DocumentFragment shouldn't be necessary

File: src/test/lib/shady-render_test.ts [hunk 25]
```diff
@@ -22,50 +22,144 @@ const assert = chai.assert;
...
+    assert.equal(getComputedStyle(div as HTMLElement).getPropertyValue('border-top-width').trim(), '4px');
```
Comment (justinfagnani) [inline src/test/lib/shady-render_test.ts]: the cast to `HTMLElement` shouldn't be necessary either, as `.querySelector('div')` is typed to return a `HTMLDivElement`

File: src/test/lib/shady-render_test.ts [hunk 26]
```diff
@@ -22,50 +22,144 @@ const assert = chai.assert;
...
+        <style>
+          div {
+            border: ${border};
+          }
+        </style>
+        <div>Testing...</div>
+      `, container.shadowRoot as DocumentFragment, 'scope-3');
+    }
+    renderTemplate('1px solid black');
+    const div = (container.shadowRoot  as DocumentFragment).querySelector('div');
```
Comment (justinfagnani) [inline src/test/lib/shady-render_test.ts]: some extra spaces in here, make sure to run `npm run format`

File: test/index.html [hunk 27]
```diff
@@ -13,9 +13,12 @@
     <script type="module" src="./lib/unsafe-html_test.js"></script>
     <script type="module" src="./lib/async-append_test.js"></script>
     <script type="module" src="./lib/async-replace_test.js"></script>
+    <script type="module" src="./lib/modify-template_test.js"></script>
     <script>
       WCT.loadSuites([
         'shady.html',
+        'shady.html?shadydom=true',
```
Comment (justinfagnani) [inline test/index.html]: I keep forgetting about this... I wonder if we should do this for all the tests?

File: src/lib/modify-template.ts (hunk 15 above)
Comment (sorvell) [reply src/lib/modify-template.ts]: Since you can't change the walker root node, this doesn't seem worth trying since there'd be more code to re-use the same walker.

File: src/lib/modify-template.ts (hunk 16 above)
Comment (sorvell) [reply src/lib/modify-template.ts]: done

File: src/lib/modify-template.ts (hunk 17 above)
Comment (sorvell) [reply src/lib/modify-template.ts]: done

File: src/lib/shady-render.ts (hunk 18 above)
Comment (sorvell) [reply src/lib/shady-render.ts]: done

File: src/lib/shady-render.ts (hunk 19 above)
Comment (sorvell) [reply src/lib/shady-render.ts]: done

File: src/lib/shady-render.ts (hunk 20 above)
Comment (sorvell) [reply src/lib/shady-render.ts]: done

File: src/lib/shady-render.ts (hunk 21 above)
Comment (sorvell) [reply src/lib/shady-render.ts]: done

File: src/lib/shady-render.ts (hunk 22 above)
Comment (sorvell) [reply src/lib/shady-render.ts]: done

File: src/lib/shady-render.ts (hunk 23 above)
Comment (sorvell) [reply src/lib/shady-render.ts]: done

File: src/test/lib/shady-render_test.ts (hunk 24 above)
Comment (sorvell) [reply src/test/lib/shady-render_test.ts]: done

File: src/test/lib/shady-render_test.ts (hunk 25 above)
Comment (sorvell) [reply src/test/lib/shady-render_test.ts]: done

File: src/test/lib/shady-render_test.ts (hunk 26 above)
Comment (sorvell) [reply src/test/lib/shady-render_test.ts]: Had trouble with this: running the formatter resulted in a lot of diffs.

File: test/index.html (hunk 27 above)
Comment (sorvell) [reply test/index.html]: let's revisit later.
